/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
  }
}

// For TSX support
declare global {
  const Counter: typeof import('./src/components/Counter.vue')['default']
  const NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
  const NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
  const NutInput: typeof import('@nutui/nutui-taro')['Input']
  const NutPopup: typeof import('@nutui/nutui-taro')['Popup']
}